<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

  <!-- properties -->
  <xacro:property name="wl_ldr_base" value="0.0556"/>
<<<<<<< HEAD
=======
  <xacro:property name="h_offset" value="0.103"/>
  <xacro:property name="l_offset" value="-0.07"/>
>>>>>>> 8dfc5c0d7a9da5742bd655b1c45715c0cc800bc5
  <xacro:property name="h_ldr_base" value="0.0231"/>
  <xacro:property name="r_ldr_top" value="${wl_ldr_base/2 - 0.001}"/>
  <xacro:property name="h_ldr_top" value="0.0182"/>
  <xacro:property name="m_ldr_base" value="0.1"/>
  <xacro:property name="m_ldr_top" value="0.1"/>
  <xacro:property name="h_ldr_trans" value="0.0298"/>
<<<<<<< HEAD
  <xacro:property name="material" value="blue"/>
=======
  <xacro:property name="color" value="blue"/>
>>>>>>> 8dfc5c0d7a9da5742bd655b1c45715c0cc800bc5

  <!-- joints and links -->
  <joint name="laser_base_joint" type="fixed">
    <parent link="chassis"/>
    <child link="laser_base_link"/>
<<<<<<< HEAD
    <origin xyz="${l_chs/3} 0 ${h_chs/2}" rpy="0 0 0"/>
=======
    <origin xyz="${l_offset} 0 ${h_chs/2 + h_offset}" rpy="0 0 0"/>
>>>>>>> 8dfc5c0d7a9da5742bd655b1c45715c0cc800bc5
  </joint>
  
  <!-- radar base is the box -->
  <link name="laser_base_link">
    <visual>
      <origin xyz="0.0 0.0 ${h_ldr_base/2}"/>  <!-- because joint is offset from base-link-->
      <geometry>
        <box size="${wl_ldr_base} ${wl_ldr_base} ${h_ldr_base}"/>
      </geometry>
<<<<<<< HEAD
      <material name="${material}"/>
=======
      <material name="${color}"/>
>>>>>>> 8dfc5c0d7a9da5742bd655b1c45715c0cc800bc5
    </visual>
    <collision>
      <origin xyz="0.0 0.0 ${h_ldr_base/2}"/>  <!-- because joint is offset from base-link-->
      <geometry>
        <box size="${wl_ldr_base} ${wl_ldr_base} ${h_ldr_base}"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="${m_ldr_base}" x="${wl_ldr_base}" y="${wl_ldr_base}" z="${h_ldr_base}">
      <!-- cog in center of box -->
      <origin xyz="0.0 0.0 ${h_ldr_base/2}" rpy="0 0 0"/>  <!-- because joint is offset from base-link-->
    </xacro:inertial_box>
  </link>

  <joint name="laser_top_joint" type="fixed">
    <parent link="laser_base_link"/>
    <child link="laser_top_link"/>
    <origin xyz="0.0 0.0 ${h_ldr_base}" rpy="0 0 0"/>
  </joint>
  
  <!-- radar top is a cylinkder -->
  <link name="laser_top_link">
    <visual>
      <origin xyz="0 0 ${h_ldr_top/2}"/>
      <geometry>
        <cylinder radius="${r_ldr_top}" length="${h_ldr_top}"/>
      </geometry>
<<<<<<< HEAD
      <material name="black"/>
=======
      <material name="${color}"/>
>>>>>>> 8dfc5c0d7a9da5742bd655b1c45715c0cc800bc5
    </visual>
    
    <collision>
      <geometry>
        <cylinder radius="${r_ldr_top}" length="${h_ldr_top}"/>
      </geometry>
    </collision>
  </link>
  
  <!-- the actual lidar frame -->
  <joint name="laser_transducer_joint" type="fixed">
    <parent link="laser_base_link"/>
    <child link="laser_transducer_frame"/>
<<<<<<< HEAD
    <origin xyz="0.0 0.0 ${h_ldr_trans}" rpy="0 0.0 ${pi/2}"/>
=======
    <origin xyz="0.0 0.0 ${h_ldr_trans}" rpy="0 0 3.1416"/>  <!-- 180 degrees because lidar is oriented wrong -->
>>>>>>> 8dfc5c0d7a9da5742bd655b1c45715c0cc800bc5
  </joint>

  <link name="laser_transducer_frame">
  </link>



<<<<<<< HEAD
  <!-- ================================================== -->
  <!-- ============  GAZEBO STUFF  ====================== -->
  <!-- ================================================== -->
  <gazebo reference="laser_transducer_frame">
    <sensor name="lidar_c3" type="ray">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14</min_angle>
            <max_angle>3.14</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.05</min>
          <max>12.0</max>
          <resolution>0.015</resolution>
        </range>
      </ray>
      <plugin name="lidar_controller" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <argument>~/out:=scan</argument>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>laser_transducer_frame</frame_name>
      </plugin>
    </sensor>
  </gazebo>

=======
>>>>>>> 8dfc5c0d7a9da5742bd655b1c45715c0cc800bc5
</robot>