generic_parameters:
  dimensions:
    chassis_length: 0.40
    chassis_width: 0.30
    chassis_height: 0.15

    wheel_diameter: 0.142
    offset_wheel_to_chassis: 0.019
    wheel_separation: {{chassis_length + offset_wheel2chassis}}
motors:
  no_load_rpm: 150.0