controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true

    # set up the actual controllers. first name, then the type
    diff_cont:  # user chosen name
        type: diff_drive_controller/DiffDriveController

    # joint state broadcaster (controller that doesn't control anything)
    joint_broad:
        type: joint_state_broadcaster/JointStateBroadcaster


# parameters for the actual controllers (childs of controller manager)
diff_cont:
  ros__parameters:
    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.338
    wheel_radius: 0.071

    use_stamped_vel: false

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0  # based on 120 rpm plus wheel diameter of 14.2 cm
        has_acceleration_limits: true
        max_acceleration: 0.5  # spec says 1, but I'll stay safe

    angular:
      z:
        has_velocity_limits: true
        max_velocity: 5.3  # based on maximum linear velocity, wheel diameter and wheel offset
        has_acceleration_limits: true
        max_acceleration: 3.14  # sI had to guess those

# joint_broad:
#     ros__parameters:
    