controller_manager:
  ros__parameters:
    update_rate: 30
<<<<<<< HEAD
    use_sim_time: true
=======
    # use_sim_time: true
>>>>>>> 8dfc5c0d7a9da5742bd655b1c45715c0cc800bc5

    # set up the actual controllers. first name, then the type
    diff_cont:  # user chosen name
        type: diff_drive_controller/DiffDriveController

    # joint state broadcaster (controller that doesn't control anything)
    joint_broad:
        type: joint_state_broadcaster/JointStateBroadcaster


# parameters for the actual controllers (childs of controller manager)
diff_cont:
  ros__parameters:
    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
<<<<<<< HEAD
    wheel_separation: 0.402
    wheel_radius: 0.0722

    use_stamped_vel: false

    # some defaults for jazzy
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    position_feedback: false
    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5 # seconds
    publish_limited_velocity: true
    velocity_rolling_window_size: 10

    linear.x.has_velocity_limits: false
    linear.x.has_acceleration_limits: false
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 0.0
    linear.x.min_velocity: 0.0
    linear.x.max_acceleration: 0.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: false
    angular.z.has_acceleration_limits: false
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 0.0
    angular.z.min_velocity: 0.0
    angular.z.max_acceleration: 0.0
    angular.z.min_acceleration: 0.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0
=======
    wheel_separation: 0.338
    wheel_radius: 0.071

    use_stamped_vel: false

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0  # based on 120 rpm plus wheel diameter of 14.2 cm
        has_acceleration_limits: true
        max_acceleration: 0.25  # spec says 1, but I'll stay safe

    angular:
      z:
        has_velocity_limits: true
        max_velocity: 5.3  # based on maximum linear velocity, wheel diameter and wheel offset
        has_acceleration_limits: true
        max_acceleration: 3.14  # sI had to guess those
>>>>>>> 8dfc5c0d7a9da5742bd655b1c45715c0cc800bc5

# joint_broad:
#     ros__parameters:
    