controller_manager:
  ros__parameters:
    update_rate: 30.0
    use_sim_time: true

    # set up the actual controllers. first name, then the type
    diff_cont:  # user chosen name
        type: diff_drive_controller/DiffDriveController

    # joint state broadcaster (controller that doesn't control anything)
    joint_broad:
        type: joint_state_broadcaster/JointStateBroadcaster


# parameters for the actual controllers (childs of controller manager)
diff_cont:
  ros__parameters:
    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.35
    wheel_radius: 0.05

    use_stamped_vel: false

# joint_broad:
#     ros__parameters:
    